### ISSUE TITLE
Poster renamerr fatal error

### ISSUE THREAD

**Issue by christophedc0** [Drazzilb08/daps#143]
```03/29/24 03:28 PM INFO:
*********************** POSTER RENAMERR Version: 1.0.5 ***********************

03/29/24 03:28 PM INFO: Running POSTER RENAMERR
03/29/24 03:28 PM INFO:
*************************** START POSTER 
03/29/24 03:28 PM INFO: Running sync_gdrive
03/29/24 03:31 PM INFO: Finished running sync_gdrive
03/29/24 03:41 PM ERROR:

An error occurred:
Traceback (most recent call last):
File "/app/modules/poster_renamerr.py", line 652, in main
output = rename_files(matched_assets, script_config, logger)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/modules/poster_renamerr.py", line 285, in rename_files
season_number = (re.search(r"Season (\d+)", file_name).group(1) if "Season" in file_name else "00").zfill(2)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
03/29/24 03:41 PM ERROR:


03/29/24 03:41 PM INFO:
**************************** END POSTER RENAMERR *****************************
```

Please add error handling :)

**Comment by christophedc0** [comment]
Log from debug:

```            

        "series": [
            {
                "title": "Batman: Caped Crusader",
                "year": 0,
                "folder": "Batman Caped Crusader {imdb-tt14681596}"
            },
            {
                "title": "Floor Is Lava",
                "year": 2020,
                "folder": "Floor Is Lava (2020) {imdb-tt12370124}"
            },
            {
                "title": "Dark Matter",
                "year": 2024,
                "folder": "Dark Matter (2024) {imdb-tt19231492}"
            },
            {
                "title": "Neuromancer",
                "year": 0,
                "folder": "Neuromancer {imdb-tt31512174}"
            }
        ]
    }
}

An error occurred:
Traceback (most recent call last):
  File "/app/modules/poster_renamerr.py", line 652, in main
    output = rename_files(matched_assets, script_config, logger)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/modules/poster_renamerr.py", line 285, in rename_files
    season_number = (re.search(r"Season (\d+)", file_name).group(1) if "Season" in file_name else "00").zfill(2)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
```

Not sure if fails on Neuromancer or what is coming after that ?

**Comment by christophedc0** [comment]
Update:
Issue was related to a file named: `Black Spot (2017) - Season1.jpg` 
Renaming it to `Black Spot (2017) - Season 1.jpg` fixed the issue

Notice the <space> between Season and the Season Number.
